os: linux
dist: jammy
language: php
php:
  - 8.2

cache:
  npm: true
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn"
  - "./private/node_modules"
  - "./vendor"

before_install:
- phpenv config-rm xdebug.ini

install:
- composer install
- nvm install 20 && nvm use 20
- corepack enable
- cd private && yarn && cd ..

stages:
  - name: Lint
    if: branch IS present
  - name: Update Draft Release [DEV]
    if: branch = develop AND type != pull_request
  - name: Update Draft Release [STG]
    if: branch = staging AND type != pull_request
  - name: Update Draft Release [PRD]
    if: branch = main AND type != pull_request

jobs:
  include:
  - stage: Lint
    script:
    - cd private && yarn && yarn build && cd ..
    - composer lint

  - stage: Update Draft Release [DEV]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-petitions-develop.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "Li9eyjt2I+tTaFdYtuQvZVRizGS4fnZOyqUxggw6mbOyrvLj5nw4eqi4JPpkO9fWCrf5klFIJ6sb5ikQcwf+mYkn1G8msHBHDe/hlcZJxFyuCs1QykU4LTYZCti9mR6lPCkCmAjTqUzvzZt9Y9aB047ReGiXu11JQNVX2gb1LB3j6Bjmqx2VvrwmNgnsQIL5djGQaH+Dm1Az1iunZnU04+YmGQc0NcVypOYwzBMCIhA9vXatO0FAUkf8I274QmVWAato+iRF8cqcG4Hdn6rLqCZWTEw31VUcKF7KBKJxIh1f1fL9ohIGEquIeulj7FjgT0pzgqq2dRl0vIm2fCD4mdqhgoPAmmhbDQAoy5wwzBRfi8W2hr3tTj1Zd6Vw6jgSfDw/X81ERF6Wwm+6SbzRMpdovmYSC+v2tE6cAzCMbAj2w3yJdA+yyO/eN42kGlhgFHzgn1j872JahgEXLHNvEJNpPvpUef0laTDxTPRL7R6Zn3SoJi9ujUakuQU5jnd8bbpz10fPsMppDe7LLfCWKkENfZ0LvtNbKvqIazfwxRbKY7BgPCU/nGiLdumw5T2e0UghYd1BZku5sOfqqJaHLKj/U5BYwEAh/9M3k4aeek5+0sge5XrdVVhIPtcFcNm1ztrZHwfOEyfZOWwC2gIzZlfL9MZImm5xoBO3wiLcSPs="
      file: "../humanity-petitions-develop.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions
        branch: develop

  - stage: Update Draft Release [STG]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-petitions-staging.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "Li9eyjt2I+tTaFdYtuQvZVRizGS4fnZOyqUxggw6mbOyrvLj5nw4eqi4JPpkO9fWCrf5klFIJ6sb5ikQcwf+mYkn1G8msHBHDe/hlcZJxFyuCs1QykU4LTYZCti9mR6lPCkCmAjTqUzvzZt9Y9aB047ReGiXu11JQNVX2gb1LB3j6Bjmqx2VvrwmNgnsQIL5djGQaH+Dm1Az1iunZnU04+YmGQc0NcVypOYwzBMCIhA9vXatO0FAUkf8I274QmVWAato+iRF8cqcG4Hdn6rLqCZWTEw31VUcKF7KBKJxIh1f1fL9ohIGEquIeulj7FjgT0pzgqq2dRl0vIm2fCD4mdqhgoPAmmhbDQAoy5wwzBRfi8W2hr3tTj1Zd6Vw6jgSfDw/X81ERF6Wwm+6SbzRMpdovmYSC+v2tE6cAzCMbAj2w3yJdA+yyO/eN42kGlhgFHzgn1j872JahgEXLHNvEJNpPvpUef0laTDxTPRL7R6Zn3SoJi9ujUakuQU5jnd8bbpz10fPsMppDe7LLfCWKkENfZ0LvtNbKvqIazfwxRbKY7BgPCU/nGiLdumw5T2e0UghYd1BZku5sOfqqJaHLKj/U5BYwEAh/9M3k4aeek5+0sge5XrdVVhIPtcFcNm1ztrZHwfOEyfZOWwC2gIzZlfL9MZImm5xoBO3wiLcSPs="
      file: "../humanity-petitions-staging.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions
        branch: staging

  - stage: Update Draft Release [PRD]
    script:
    - cd private && yarn && yarn build && cd ..
    - zip -r ../humanity-petitions.zip ./ -x docs\* -x private\* -x vendor\* -x .\* -x CHANGELOG.md -x CODE_OF_CONDUCT.md -x composer.json -x composer.lock -x CONTRIBUTING.md -x LICENSE.md -x phpcs.xml -x SECURITY.md
    deploy:
      provider: releases
      token:
        secure: "Li9eyjt2I+tTaFdYtuQvZVRizGS4fnZOyqUxggw6mbOyrvLj5nw4eqi4JPpkO9fWCrf5klFIJ6sb5ikQcwf+mYkn1G8msHBHDe/hlcZJxFyuCs1QykU4LTYZCti9mR6lPCkCmAjTqUzvzZt9Y9aB047ReGiXu11JQNVX2gb1LB3j6Bjmqx2VvrwmNgnsQIL5djGQaH+Dm1Az1iunZnU04+YmGQc0NcVypOYwzBMCIhA9vXatO0FAUkf8I274QmVWAato+iRF8cqcG4Hdn6rLqCZWTEw31VUcKF7KBKJxIh1f1fL9ohIGEquIeulj7FjgT0pzgqq2dRl0vIm2fCD4mdqhgoPAmmhbDQAoy5wwzBRfi8W2hr3tTj1Zd6Vw6jgSfDw/X81ERF6Wwm+6SbzRMpdovmYSC+v2tE6cAzCMbAj2w3yJdA+yyO/eN42kGlhgFHzgn1j872JahgEXLHNvEJNpPvpUef0laTDxTPRL7R6Zn3SoJi9ujUakuQU5jnd8bbpz10fPsMppDe7LLfCWKkENfZ0LvtNbKvqIazfwxRbKY7BgPCU/nGiLdumw5T2e0UghYd1BZku5sOfqqJaHLKj/U5BYwEAh/9M3k4aeek5+0sge5XrdVVhIPtcFcNm1ztrZHwfOEyfZOWwC2gIzZlfL9MZImm5xoBO3wiLcSPs="
      file: "../humanity-petitions.zip"
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        repo: amnestywebsite/humanity-petitions
        branch: main
